mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/EGM_Bin1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/EGM_Bin2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/F_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM45_Bin1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM45_Bin2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM58_Bin_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM79_Bin_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM81_Bin1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM81_Bin2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM82_Bin1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/HM82_Bin2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/SB_01_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/SB_02_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/SMM_01_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/XS83_01_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/XS83_02_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/XS87_01_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/XS87_02_renamed.fa.fasta.TCDB.m8 ./
