prodigal -p single -i ./Haladaptatus_paucihalophilus_DX253_renamed.fa -d Haladaptatus_paucihalophilus_DX253_renamed.fa.fasta -a Haladaptatus_paucihalophilus_DX253_renamed.fa.faa
prodigal -p single -i ./Methanocella_arvoryzae_MRE50_renamed.fa -d Methanocella_arvoryzae_MRE50_renamed.fa.fasta -a Methanocella_arvoryzae_MRE50_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa -d Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa.fasta -a Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_strain_DS1_renamed.fa -d Thaumarchaeota_archaeon_strain_DS1_renamed.fa.fasta -a Thaumarchaeota_archaeon_strain_DS1_renamed.fa.faa
prodigal -p single -i ./Halorhabdus_utahensis_DSM_12940_renamed.fa -d Halorhabdus_utahensis_DSM_12940_renamed.fa.fasta -a Halorhabdus_utahensis_DSM_12940_renamed.fa.faa
prodigal -p single -i ./Nitrosopelagicus_sp_REDSEA-S31_B2_renamed.fa -d Nitrosopelagicus_sp_REDSEA-S31_B2_renamed.fa.fasta -a Nitrosopelagicus_sp_REDSEA-S31_B2_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_strain_BS3_renamed.fa -d Thaumarchaeota_archaeon_strain_BS3_renamed.fa.fasta -a Thaumarchaeota_archaeon_strain_BS3_renamed.fa.faa
prodigal -p single -i ./Nitrososphaera_viennensis_EN76_renamed.fa -d Nitrososphaera_viennensis_EN76_renamed.fa.fasta -a Nitrososphaera_viennensis_EN76_renamed.fa.faa
prodigal -p single -i ./XS83_02_renamed.fa -d XS83_02_renamed.fa.fasta -a XS83_02_renamed.fa.faa
prodigal -p single -i ./Nitrosocosmicus_oleophilus_strain_MY3_renamed.fa -d Nitrosocosmicus_oleophilus_strain_MY3_renamed.fa.fasta -a Nitrosocosmicus_oleophilus_strain_MY3_renamed.fa.faa
prodigal -p single -i ./HM45_Bin2_renamed.fa -d HM45_Bin2_renamed.fa.fasta -a HM45_Bin2_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_adriaticus_strain_NF5_renamed.fa -d Nitrosopumilus_adriaticus_strain_NF5_renamed.fa.fasta -a Nitrosopumilus_adriaticus_strain_NF5_renamed.fa.faa
prodigal -p single -i ./Pyrobaculum_islandicum_DSM_4184_renamed.fa -d Pyrobaculum_islandicum_DSM_4184_renamed.fa.fasta -a Pyrobaculum_islandicum_DSM_4184_renamed.fa.faa
prodigal -p single -i ./Nitrososphaera_evergladensis_SR1_renamed.fa -d Nitrososphaera_evergladensis_SR1_renamed.fa.fasta -a Nitrososphaera_evergladensis_SR1_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_sp_DDS1_renamed.fa -d Nitrosopumilus_sp_DDS1_renamed.fa.fasta -a Nitrosopumilus_sp_DDS1_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_koreensis_AR1_renamed.fa -d Nitrosopumilus_koreensis_AR1_renamed.fa.fasta -a Nitrosopumilus_koreensis_AR1_renamed.fa.faa
prodigal -p single -i ./Picrophilus_torridus_DSM_9790_renamed.fa -d Picrophilus_torridus_DSM_9790_renamed.fa.fasta -a Picrophilus_torridus_DSM_9790_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_CSP1-1.fa -d Thaumarchaeota_CSP1-1.fa.fasta -a Thaumarchaeota_CSP1-1.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_UBA183_renamed.fa -d Thaumarchaeota_archaeon_UBA183_renamed.fa.fasta -a Thaumarchaeota_archaeon_UBA183_renamed.fa.faa
prodigal -p single -i ./Pyrococcus_abyssi_GE5_renamed.fa -d Pyrococcus_abyssi_GE5_renamed.fa.fasta -a Pyrococcus_abyssi_GE5_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed.fa.faa
prodigal -p single -i ./Aigarchaeota_archaeon_NZ13_MG1_renamed.fa -d Aigarchaeota_archaeon_NZ13_MG1_renamed.fa.fasta -a Aigarchaeota_archaeon_NZ13_MG1_renamed.fa.faa
prodigal -p single -i ./Sulfolobus_islandicus_L_D_8_5_renamed.fa -d Sulfolobus_islandicus_L_D_8_5_renamed.fa.fasta -a Sulfolobus_islandicus_L_D_8_5_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_maritimus_SCM1_renamed.fa -d Nitrosopumilus_maritimus_SCM1_renamed.fa.fasta -a Nitrosopumilus_maritimus_SCM1_renamed.fa.faa
prodigal -p single -i ./Thermoproteus_tenax_Kra_1_renamed.fa -d Thermoproteus_tenax_Kra_1_renamed.fa.fasta -a Thermoproteus_tenax_Kra_1_renamed.fa.faa
prodigal -p single -i ./XS87_01_renamed.fa -d XS87_01_renamed.fa.fasta -a XS87_01_renamed.fa.faa
prodigal -p single -i ./Unclassified_Aigarchaeota_JZ_bin_40_renamed.fa -d Unclassified_Aigarchaeota_JZ_bin_40_renamed.fa.fasta -a Unclassified_Aigarchaeota_JZ_bin_40_renamed.fa.faa
prodigal -p single -i ./Methanocorpusculum_labreanum_Z_renamed.fa -d Methanocorpusculum_labreanum_Z_renamed.fa.fasta -a Methanocorpusculum_labreanum_Z_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed.fa.faa
prodigal -p single -i ./Thermococcus_litoralis_DSM_5473_renamed.fa -d Thermococcus_litoralis_DSM_5473_renamed.fa.fasta -a Thermococcus_litoralis_DSM_5473_renamed.fa.faa
prodigal -p single -i ./Nitrosocosmicus_hydrocola_strain_G61_renamed.fa -d Nitrosocosmicus_hydrocola_strain_G61_renamed.fa.fasta -a Nitrosocosmicus_hydrocola_strain_G61_renamed.fa.faa
prodigal -p single -i ./Aciduliprofundum_boonei_T469_renamed.fa -d Aciduliprofundum_boonei_T469_renamed.fa.fasta -a Aciduliprofundum_boonei_T469_renamed.fa.faa
prodigal -p single -i ./Pyrococcus_furiosus_DSM_3638_2_renamed.fa -d Pyrococcus_furiosus_DSM_3638_2_renamed.fa.fasta -a Pyrococcus_furiosus_DSM_3638_2_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed.fa.faa
prodigal -p single -i ./Thermoplasma_acidophilum_DSM_1728_renamed.fa -d Thermoplasma_acidophilum_DSM_1728_renamed.fa.fasta -a Thermoplasma_acidophilum_DSM_1728_renamed.fa.faa
prodigal -p single -i ./Saccharolobus_solfataricus_P2_renamed.fa -d Saccharolobus_solfataricus_P2_renamed.fa.fasta -a Saccharolobus_solfataricus_P2_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_UBA160_renamed.fa -d Thaumarchaeota_archaeon_UBA160_renamed.fa.fasta -a Thaumarchaeota_archaeon_UBA160_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_bin_Fn1_renamed.fa -d Thaumarchaeota_bin_Fn1_renamed.fa.fasta -a Thaumarchaeota_bin_Fn1_renamed.fa.faa
prodigal -p single -i ./AAA288-D22_renamed.fa -d AAA288-D22_renamed.fa.fasta -a AAA288-D22_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_sp_Nsub_renamed.fa -d Nitrosopumilus_sp_Nsub_renamed.fa.fasta -a Nitrosopumilus_sp_Nsub_renamed.fa.faa
prodigal -p single -i ./HM45_Bin1_renamed.fa -d HM45_Bin1_renamed.fa.fasta -a HM45_Bin1_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_UBA164_renamed.fa -d Thaumarchaeota_archaeon_UBA164_renamed.fa.fasta -a Thaumarchaeota_archaeon_UBA164_renamed.fa.faa
prodigal -p single -i ./Nitrosoarchaeum-Baikal-G1-C1_renamed.fa -d Nitrosoarchaeum-Baikal-G1-C1_renamed.fa.fasta -a Nitrosoarchaeum-Baikal-G1-C1_renamed.fa.faa
prodigal -p single -i ./Pyrobaculum_arsenaticum_DSM_13514_renamed.fa -d Pyrobaculum_arsenaticum_DSM_13514_renamed.fa.fasta -a Pyrobaculum_arsenaticum_DSM_13514_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_sp_D3C_renamed.fa -d Nitrosopumilus_sp_D3C_renamed.fa.fasta -a Nitrosopumilus_sp_D3C_renamed.fa.faa
prodigal -p single -i ./Methanotorris_igneus_Kol_5_renamed.fa -d Methanotorris_igneus_Kol_5_renamed.fa.fasta -a Methanotorris_igneus_Kol_5_renamed.fa.faa
prodigal -p single -i ./Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed.fa -d Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed.fa.fasta -a Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed.fa.faa
prodigal -p single -i ./Pyrobaculum_aerophilum_str_IM2_renamed.fa -d Pyrobaculum_aerophilum_str_IM2_renamed.fa.fasta -a Pyrobaculum_aerophilum_str_IM2_renamed.fa.faa
prodigal -p single -i ./Methanothermus_fervidus_DSM_2088_renamed.fa -d Methanothermus_fervidus_DSM_2088_renamed.fa.fasta -a Methanothermus_fervidus_DSM_2088_renamed.fa.faa
prodigal -p single -i ./Nitrosotenuis_chungbukensis_MY2_renamed.fa -d Nitrosotenuis_chungbukensis_MY2_renamed.fa.fasta -a Nitrosotenuis_chungbukensis_MY2_renamed.fa.faa
prodigal -p single -i ./Candidatus_Nitrosocosmicus_franklandus_C13_renamed.fa -d Candidatus_Nitrosocosmicus_franklandus_C13_renamed.fa.fasta -a Candidatus_Nitrosocosmicus_franklandus_C13_renamed.fa.faa
prodigal -p single -i ./Thermoplasma_volcanium_GSS1_renamed.fa -d Thermoplasma_volcanium_GSS1_renamed.fa.fasta -a Thermoplasma_volcanium_GSS1_renamed.fa.faa
prodigal -p single -i ./Candidatus_Caldiarchaeum_subterraneum_renamed.fa -d Candidatus_Caldiarchaeum_subterraneum_renamed.fa.fasta -a Candidatus_Caldiarchaeum_subterraneum_renamed.fa.faa
prodigal -p single -i ./SB_02_renamed.fa -d SB_02_renamed.fa.fasta -a SB_02_renamed.fa.faa
prodigal -p single -i ./SMM_01_renamed.fa -d SMM_01_renamed.fa.fasta -a SMM_01_renamed.fa.faa
prodigal -p single -i ./Nitrosotalea_bavarica_SbT1_renamed.fa -d Nitrosotalea_bavarica_SbT1_renamed.fa.fasta -a Nitrosotalea_bavarica_SbT1_renamed.fa.faa
prodigal -p single -i ./Nitrosarchaeum_limnium_SFB1_renamed.fa -d Nitrosarchaeum_limnium_SFB1_renamed.fa.fasta -a Nitrosarchaeum_limnium_SFB1_renamed.fa.faa
prodigal -p single -i ./Vulcanisaeta_distributa_DSM_14429_renamed.fa -d Vulcanisaeta_distributa_DSM_14429_renamed.fa.fasta -a Vulcanisaeta_distributa_DSM_14429_renamed.fa.faa
prodigal -p single -i ./AAA007-N19_renamed.fa -d AAA007-N19_renamed.fa.fasta -a AAA007-N19_renamed.fa.faa
prodigal -p single -i ./Nitrosoarchaeum_sp_BD3_renamed.fa -d Nitrosoarchaeum_sp_BD3_renamed.fa.fasta -a Nitrosoarchaeum_sp_BD3_renamed.fa.faa
prodigal -p single -i ./Nitrosotenuis_cloacae_strain_SAT1_renamed.fa -d Nitrosotenuis_cloacae_strain_SAT1_renamed.fa.fasta -a Nitrosotenuis_cloacae_strain_SAT1_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_UBA57_renamed.fa -d Thaumarchaeota_archaeon_UBA57_renamed.fa.fasta -a Thaumarchaeota_archaeon_UBA57_renamed.fa.faa
prodigal -p single -i ./Nitrosopelagicus_brevis_strain_CN25_renamed.fa -d Nitrosopelagicus_brevis_strain_CN25_renamed.fa.fasta -a Nitrosopelagicus_brevis_strain_CN25_renamed.fa.faa
prodigal -p single -i ./Candidatus_Nitrosopumilus_sp_MTA1_renamed.fa -d Candidatus_Nitrosopumilus_sp_MTA1_renamed.fa.fasta -a Candidatus_Nitrosopumilus_sp_MTA1_renamed.fa.faa
prodigal -p single -i ./HM82_Bin1_renamed.fa -d HM82_Bin1_renamed.fa.fasta -a HM82_Bin1_renamed.fa.faa
prodigal -p single -i ./Halorubrum_lacusprofundi_ATCC_49239_renamed.fa -d Halorubrum_lacusprofundi_ATCC_49239_renamed.fa.fasta -a Halorubrum_lacusprofundi_ATCC_49239_renamed.fa.faa
prodigal -p single -i ./Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa -d Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa.fasta -a Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilus_salaria_BD31_renamed.fa -d Nitrosopumilus_salaria_BD31_renamed.fa.fasta -a Nitrosopumilus_salaria_BD31_renamed.fa.faa
prodigal -p single -i ./Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed.fa -d Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed.fa.fasta -a Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed.fa.faa
prodigal -p single -i ./HM58_Bin_renamed.fa -d HM58_Bin_renamed.fa.fasta -a HM58_Bin_renamed.fa.faa
prodigal -p single -i ./Ferroplasma_acidarmanus_fer1_renamed.fa -d Ferroplasma_acidarmanus_fer1_renamed.fa.fasta -a Ferroplasma_acidarmanus_fer1_renamed.fa.faa
prodigal -p single -i ./XS83_01_renamed.fa -d XS83_01_renamed.fa.fasta -a XS83_01_renamed.fa.faa
prodigal -p single -i ./Pyrococcus_yayanosii_CH1_renamed.fa -d Pyrococcus_yayanosii_CH1_renamed.fa.fasta -a Pyrococcus_yayanosii_CH1_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_isolate_MTA5_renamed.fa -d Thaumarchaeota_archaeon_isolate_MTA5_renamed.fa.fasta -a Thaumarchaeota_archaeon_isolate_MTA5_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed.fa.faa
prodigal -p single -i ./Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed.fa -d Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed.fa.fasta -a Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed.fa.faa
prodigal -p single -i ./Thermococcus_barophilus_MP_renamed.fa -d Thermococcus_barophilus_MP_renamed.fa.fasta -a Thermococcus_barophilus_MP_renamed.fa.faa
prodigal -p single -i ./Natronomonas_pharaonis_DSM_2160_renamed.fa -d Natronomonas_pharaonis_DSM_2160_renamed.fa.fasta -a Natronomonas_pharaonis_DSM_2160_renamed.fa.faa
prodigal -p single -i ./Candidatus_Korarchaeum_cryptofilum_OPF8_renamed.fa -d Candidatus_Korarchaeum_cryptofilum_OPF8_renamed.fa.fasta -a Candidatus_Korarchaeum_cryptofilum_OPF8_renamed.fa.faa
prodigal -p single -i ./Methanopyrus_kandleri_AV19_renamed.fa -d Methanopyrus_kandleri_AV19_renamed.fa.fasta -a Methanopyrus_kandleri_AV19_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed.fa.faa
prodigal -p single -i ./HM81_Bin2_renamed.fa -d HM81_Bin2_renamed.fa.fasta -a HM81_Bin2_renamed.fa.faa
prodigal -p single -i ./Thermofilum_pendens_Hrk_5_renamed.fa -d Thermofilum_pendens_Hrk_5_renamed.fa.fasta -a Thermofilum_pendens_Hrk_5_renamed.fa.faa
prodigal -p single -i ./HM79_Bin_renamed.fa -d HM79_Bin_renamed.fa.fasta -a HM79_Bin_renamed.fa.faa
prodigal -p single -i ./XS87_02_renamed.fa -d XS87_02_renamed.fa.fasta -a XS87_02_renamed.fa.faa
prodigal -p single -i ./Thermococcus_gammatolerans_EJ3_renamed.fa -d Thermococcus_gammatolerans_EJ3_renamed.fa.fasta -a Thermococcus_gammatolerans_EJ3_renamed.fa.faa
prodigal -p single -i ./Nitrososphaera_gargensis_Ga9_renamed.fa -d Nitrososphaera_gargensis_Ga9_renamed.fa.fasta -a Nitrososphaera_gargensis_Ga9_renamed.fa.faa
prodigal -p single -i ./EGM_Bin1_renamed.fa -d EGM_Bin1_renamed.fa.fasta -a EGM_Bin1_renamed.fa.faa
prodigal -p single -i ./Aigarchaeota_archaeon_strain_OS1_renamed.fa -d Aigarchaeota_archaeon_strain_OS1_renamed.fa.fasta -a Aigarchaeota_archaeon_strain_OS1_renamed.fa.faa
prodigal -p single -i ./Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed.fa -d Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed.fa.fasta -a Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed.fa.faa
prodigal -p single -i ./EGM_Bin2_renamed.fa -d EGM_Bin2_renamed.fa.fasta -a EGM_Bin2_renamed.fa.faa
prodigal -p single -i ./Sulfolobus_tokodaii_str_7_renamed.fa -d Sulfolobus_tokodaii_str_7_renamed.fa.fasta -a Sulfolobus_tokodaii_str_7_renamed.fa.faa
prodigal -p single -i ./F_renamed.fa -d F_renamed.fa.fasta -a F_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1.fa -d Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1.fa.fasta -a Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1.fa.faa
prodigal -p single -i ./Halogeometricum_borinquense_DSM_11551_renamed.fa -d Halogeometricum_borinquense_DSM_11551_renamed.fa.fasta -a Halogeometricum_borinquense_DSM_11551_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed.fa -d Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed.fa.fasta -a Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed.fa.faa
prodigal -p single -i ./Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed.fa -d Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed.fa.fasta -a Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed.fa.faa
prodigal -p single -i ./Marine_Group_1_crenarchaeote_sp_SCGC_renamed.fa -d Marine_Group_1_crenarchaeote_sp_SCGC_renamed.fa.fasta -a Marine_Group_1_crenarchaeote_sp_SCGC_renamed.fa.faa
prodigal -p single -i ./Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed.fa -d Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed.fa.fasta -a Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed.fa.faa
prodigal -p single -i ./Nitrosotenuis_aquarius_strain_AQ6F_renamed.fa -d Nitrosotenuis_aquarius_strain_AQ6F_renamed.fa.fasta -a Nitrosotenuis_aquarius_strain_AQ6F_renamed.fa.faa
prodigal -p single -i ./SB_01_renamed.fa -d SB_01_renamed.fa.fasta -a SB_01_renamed.fa.faa
prodigal -p single -i ./Archaeoglobus_veneficus_SNP6_renamed.fa -d Archaeoglobus_veneficus_SNP6_renamed.fa.fasta -a Archaeoglobus_veneficus_SNP6_renamed.fa.faa
prodigal -p single -i ./Nitrosomarinus_catalina_strain_SPOT01_renamed.fa -d Nitrosomarinus_catalina_strain_SPOT01_renamed.fa.fasta -a Nitrosomarinus_catalina_strain_SPOT01_renamed.fa.faa
prodigal -p single -i ./Methanosarcina_mazei_Go1_renamed.fa -d Methanosarcina_mazei_Go1_renamed.fa.fasta -a Methanosarcina_mazei_Go1_renamed.fa.faa
prodigal -p single -i ./Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed.fa.fasta -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed.fa.faa
prodigal -p single -i ./Sulfolobus_acidocaldarius_DSM_639_renamed.fa -d Sulfolobus_acidocaldarius_DSM_639_renamed.fa.fasta -a Sulfolobus_acidocaldarius_DSM_639_renamed.fa.faa
prodigal -p single -i ./Nitrosopelagicus_brevis_U25_renamed.fa -d Nitrosopelagicus_brevis_U25_renamed.fa.fasta -a Nitrosopelagicus_brevis_U25_renamed.fa.faa
prodigal -p single -i ./AAA799-O18_renamed.fa -d AAA799-O18_renamed.fa.fasta -a AAA799-O18_renamed.fa.faa
prodigal -p single -i ./Nitrosotalea_sinensis_Nd2_renamed.fa -d Nitrosotalea_sinensis_Nd2_renamed.fa.fasta -a Nitrosotalea_sinensis_Nd2_renamed.fa.faa
prodigal -p single -i ./YK1312_12N_NP_theta_renamed.fa -d YK1312_12N_NP_theta_renamed.fa.fasta -a YK1312_12N_NP_theta_renamed.fa.faa
prodigal -p single -i ./Metallosphaera_sedula_DSM_5348_renamed.fa -d Metallosphaera_sedula_DSM_5348_renamed.fa.fasta -a Metallosphaera_sedula_DSM_5348_renamed.fa.faa
prodigal -p single -i ./Nitrosarchaeum_koreense_MY1_renamed.fa -d Nitrosarchaeum_koreense_MY1_renamed.fa.fasta -a Nitrosarchaeum_koreense_MY1_renamed.fa.faa
prodigal -p single -i ./Nitrosarchaeum_limnium_BG20_renamed.fa -d Nitrosarchaeum_limnium_BG20_renamed.fa.fasta -a Nitrosarchaeum_limnium_BG20_renamed.fa.faa
prodigal -p single -i ./Caldivirga_maquilingensis_IC_167_renamed.fa -d Caldivirga_maquilingensis_IC_167_renamed.fa.fasta -a Caldivirga_maquilingensis_IC_167_renamed.fa.faa
prodigal -p single -i ./Candidatus_Nitrosocaldus_cavascurensis_strain_renamed.fa -d Candidatus_Nitrosocaldus_cavascurensis_strain_renamed.fa.fasta -a Candidatus_Nitrosocaldus_cavascurensis_strain_renamed.fa.faa
prodigal -p single -i ./Sulfolobus_solfataricus_P2_renamed.fa -d Sulfolobus_solfataricus_P2_renamed.fa.fasta -a Sulfolobus_solfataricus_P2_renamed.fa.faa
prodigal -p single -i ./Nitrosotalea_koreensis_CS_renamed.fa -d Nitrosotalea_koreensis_CS_renamed.fa.fasta -a Nitrosotalea_koreensis_CS_renamed.fa.faa
prodigal -p single -i ./Metallosphaera_yellowstonensis_MK1_renamed.fa -d Metallosphaera_yellowstonensis_MK1_renamed.fa.fasta -a Metallosphaera_yellowstonensis_MK1_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_UBA141_renamed.fa -d Thaumarchaeota_archaeon_UBA141_renamed.fa.fasta -a Thaumarchaeota_archaeon_UBA141_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_archaeon_N4_renamed.fa -d Thaumarchaeota_archaeon_N4_renamed.fa.fasta -a Thaumarchaeota_archaeon_N4_renamed.fa.faa
prodigal -p single -i ./HM82_Bin2_renamed.fa -d HM82_Bin2_renamed.fa.fasta -a HM82_Bin2_renamed.fa.faa
prodigal -p single -i ./Natrialba_magadii_ATCC_43099_renamed.fa -d Natrialba_magadii_ATCC_43099_renamed.fa.fasta -a Natrialba_magadii_ATCC_43099_renamed.fa.faa
prodigal -p single -i ./Acidianus_hospitalis_W1_renamed.fa -d Acidianus_hospitalis_W1_renamed.fa.fasta -a Acidianus_hospitalis_W1_renamed.fa.faa
prodigal -p single -i ./Aigarchaeota_archaeon_JGI_0000106_J15_renamed.fa -d Aigarchaeota_archaeon_JGI_0000106_J15_renamed.fa.fasta -a Aigarchaeota_archaeon_JGI_0000106_J15_renamed.fa.faa
prodigal -p single -i ./Nitrosotalea_devanaterra_Nd1_renamed.fa -d Nitrosotalea_devanaterra_Nd1_renamed.fa.fasta -a Nitrosotalea_devanaterra_Nd1_renamed.fa.faa
prodigal -p single -i ./Thaumarchaeota_YK1309_1N_NP_iota.fa -d Thaumarchaeota_YK1309_1N_NP_iota.fa.fasta -a Thaumarchaeota_YK1309_1N_NP_iota.fa.faa
prodigal -p single -i ./HM81_Bin1_renamed.fa -d HM81_Bin1_renamed.fa.fasta -a HM81_Bin1_renamed.fa.faa
mv ./*.fasta ./cds/
mv ./*.faa ./pro/
