prokka --cpus 0 --compliant --rfam AAA799-B03.fa --outdir AAA799-B03.fa_prokka
prokka --cpus 0 --compliant --rfam AAA799-D11.fa --outdir AAA799-D11.fa_prokka
prokka --cpus 0 --compliant --rfam AAA799-E16.fa --outdir AAA799-E16.fa_prokka
prokka --cpus 0 --compliant --rfam AAA799-N04.fa --outdir AAA799-N04.fa_prokka
prokka --cpus 0 --compliant --rfam AAA799-P11.fa --outdir AAA799-P11.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosarchaeum_koreense_MY1.fa --outdir Nitrosarchaeum_koreense_MY1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosarchaeum_limnium_BG20.fa --outdir Nitrosarchaeum_limnium_BG20.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosarchaeum_limnium_SFB1.fa --outdir Nitrosarchaeum_limnium_SFB1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosoarchaeum-Baikal-G1-C1.fa --outdir Nitrosoarchaeum-Baikal-G1-C1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosoarchaeum_sp_BD3.fa --outdir Nitrosoarchaeum_sp_BD3.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosomarinus_catalina_strain_SPOT01.fa --outdir Nitrosomarinus_catalina_strain_SPOT01.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_adriaticus_strain_NF5.fa --outdir Nitrosopumilus_adriaticus_strain_NF5.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_koreensis_AR1.fa --outdir Nitrosopumilus_koreensis_AR1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_maritimus_SCM1.fa --outdir Nitrosopumilus_maritimus_SCM1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_salaria_BD31.fa --outdir Nitrosopumilus_salaria_BD31.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_sediminis_AR2.fa --outdir Nitrosopumilus_sediminis_AR2.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_sp_D3C.fa --outdir Nitrosopumilus_sp_D3C.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_sp_DDS1.fa --outdir Nitrosopumilus_sp_DDS1.fa_prokka
prokka --cpus 0 --compliant --rfam Nitrosopumilus_sp_Nsub.fa --outdir Nitrosopumilus_sp_Nsub.fa_prokka
