pseudofinder.py annotate -g Nitrosarchaeum_limnium_SFB1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosarchaeum_limnium_SFB1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g AAA799-B03.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op AAA799-B03.fa_annotation --diamond -t 64
pseudofinder.py annotate -g AAA799-D11.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op AAA799-D11.fa_annotation --diamond -t 64
pseudofinder.py annotate -g AAA799-E16.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op AAA799-E16.fa_annotation --diamond -t 64
pseudofinder.py annotate -g AAA799-N04.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op AAA799-N04.fa_annotation --diamond -t 64
pseudofinder.py annotate -g AAA799-P11.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op AAA799-P11.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosarchaeum_koreense_MY1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosarchaeum_koreense_MY1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosarchaeum_limnium_BG20.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosarchaeum_limnium_BG20.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosoarchaeum-Baikal-G1-C1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosoarchaeum-Baikal-G1-C1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosoarchaeum_sp_BD3.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosoarchaeum_sp_BD3.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosomarinus_catalina_strain_SPOT01.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosomarinus_catalina_strain_SPOT01.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_adriaticus_strain_NF5.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_adriaticus_strain_NF5.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_koreensis_AR1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_koreensis_AR1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_maritimus_SCM1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_maritimus_SCM1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_salaria_BD31.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_salaria_BD31.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_sediminis_AR2.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_sediminis_AR2.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_sp_D3C.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_sp_D3C.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_sp_DDS1.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_sp_DDS1.fa_annotation --diamond -t 64
pseudofinder.py annotate -g Nitrosopumilus_sp_Nsub.fa_prokka/PROKKA_*.gbk -db /media/ylifc/HD-LXU3/NR_database/nr -op Nitrosopumilus_sp_Nsub.fa_annotation --diamond -t 64
