cp Nitrosarchaeum_limnium_SFB1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_maritimus_SCM1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosarchaeum_limnium_BG20.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp AAA799-B03.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp AAA799-D11.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp AAA799-E16.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp AAA799-N04.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp AAA799-P11.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosarchaeum_koreense_MY1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosoarchaeum-Baikal-G1-C1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosoarchaeum_sp_BD3.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosomarinus_catalina_strain_SPOT01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_adriaticus_strain_NF5.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_koreensis_AR1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_salaria_BD31.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_sediminis_AR2.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_sp_D3C.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_sp_DDS1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Nitrosopumilus_sp_Nsub.fa_pseudo/*_log.txt ./pseudo_log_summmary/
