mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_YK1309_1N_NP_iota.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/YK1312_12N_NP_theta_renamed.fa.fasta.TCDB.m8 ./
