prokka --cpus 0 --compliant --rfam HM79_Bin.fa --outdir HM79_Bin.fa_prokka
prokka --cpus 0 --compliant --rfam SB_02.fa --outdir SB_02.fa_prokka
prokka --cpus 0 --compliant --rfam EGM_Bin1.fa --outdir EGM_Bin1.fa_prokka
prokka --cpus 0 --compliant --rfam EGM_Bin2.fa --outdir EGM_Bin2.fa_prokka
prokka --cpus 0 --compliant --rfam F.fa --outdir F.fa_prokka
prokka --cpus 0 --compliant --rfam HM45_Bin1.fa --outdir HM45_Bin1.fa_prokka
prokka --cpus 0 --compliant --rfam HM45_Bin2.fa --outdir HM45_Bin2.fa_prokka
prokka --cpus 0 --compliant --rfam HM58_Bin.fa --outdir HM58_Bin.fa_prokka
prokka --cpus 0 --compliant --rfam HM81_Bin1.fa --outdir HM81_Bin1.fa_prokka
prokka --cpus 0 --compliant --rfam HM81_Bin2.fa --outdir HM81_Bin2.fa_prokka
prokka --cpus 0 --compliant --rfam HM82_Bin1.fa --outdir HM82_Bin1.fa_prokka
prokka --cpus 0 --compliant --rfam HM82_Bin2.fa --outdir HM82_Bin2.fa_prokka
prokka --cpus 0 --compliant --rfam SB_01.fa --outdir SB_01.fa_prokka
prokka --cpus 0 --compliant --rfam SMM_01.fa --outdir SMM_01.fa_prokka
prokka --cpus 0 --compliant --rfam XS83_01.fa --outdir XS83_01.fa_prokka
prokka --cpus 0 --compliant --rfam XS83_02.fa --outdir XS83_02.fa_prokka
prokka --cpus 0 --compliant --rfam XS87_01.fa --outdir XS87_01.fa_prokka
prokka --cpus 0 --compliant --rfam XS87_02.fa --outdir XS87_02.fa_prokka
