cp HM81_Bin1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM79_Bin.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM81_Bin2.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM82_Bin1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM82_Bin2.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp SB_01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp SMM_01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS83_01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS83_02.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS87_01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS87_02.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp SB_02.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp EGM_Bin1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp EGM_Bin2.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp F.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM45_Bin1.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM45_Bin2.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp HM58_Bin.fa_pseudo/*_log.txt ./pseudo_log_summmary/
