perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt F_renamed.fa.fasta.kegg.m8_keggano > F_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM58_Bin_renamed.fa.fasta.kegg.m8_keggano > HM58_Bin_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt SMM_01_renamed.fa.fasta.kegg.m8_keggano > SMM_01_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM82_Bin1_renamed.fa.fasta.kegg.m8_keggano > HM82_Bin1_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt XS83_02_renamed.fa.fasta.kegg.m8_keggano > XS83_02_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM79_Bin_renamed.fa.fasta.kegg.m8_keggano > HM79_Bin_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM81_Bin1_renamed.fa.fasta.kegg.m8_keggano > HM81_Bin1_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt XS87_01_renamed.fa.fasta.kegg.m8_keggano > XS87_01_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt EGM_Bin1_renamed.fa.fasta.kegg.m8_keggano > EGM_Bin1_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt SB_02_renamed.fa.fasta.kegg.m8_keggano > SB_02_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt EGM_Bin2_renamed.fa.fasta.kegg.m8_keggano > EGM_Bin2_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM45_Bin2_renamed.fa.fasta.kegg.m8_keggano > HM45_Bin2_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM81_Bin2_renamed.fa.fasta.kegg.m8_keggano > HM81_Bin2_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt XS83_01_renamed.fa.fasta.kegg.m8_keggano > XS83_01_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM45_Bin1_renamed.fa.fasta.kegg.m8_keggano > HM45_Bin1_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt XS87_02_renamed.fa.fasta.kegg.m8_keggano > XS87_02_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt HM82_Bin2_renamed.fa.fasta.kegg.m8_keggano > HM82_Bin2_renamed.fa.fasta.kegg.m8_keggano_extraced
perl ../../specific_gene_summary_kegg.pl ../../KO_specific_genes.txt SB_01_renamed.fa.fasta.kegg.m8_keggano > SB_01_renamed.fa.fasta.kegg.m8_keggano_extraced
