prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_UBA164.fa --outdir Thaumarchaeota_archaeon_UBA164.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_strain_BS3.fa --outdir Thaumarchaeota_archaeon_strain_BS3.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_strain_BS4.fa --outdir Thaumarchaeota_archaeon_strain_BS4.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_UBA141.fa --outdir Thaumarchaeota_archaeon_UBA141.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_UBA160.fa --outdir Thaumarchaeota_archaeon_UBA160.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_UBA183.fa --outdir Thaumarchaeota_archaeon_UBA183.fa_prokka
prokka --cpus 0 --compliant --rfam Thaumarchaeota_archaeon_UBA57.fa --outdir Thaumarchaeota_archaeon_UBA57.fa_prokka
prokka --cpus 0 --compliant --rfam XS84_01.fa --outdir XS84_01.fa_prokka
prokka --cpus 0 --compliant --rfam XS84_02.fa --outdir XS84_02.fa_prokka
prokka --cpus 0 --compliant --rfam XS84_03.fa --outdir XS84_03.fa_prokka
