cp Thaumarchaeota_archaeon_strain_BS4.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_UBA164.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_strain_BS3.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_UBA141.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_UBA160.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_UBA183.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp Thaumarchaeota_archaeon_UBA57.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS84_01.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS84_02.fa_pseudo/*_log.txt ./pseudo_log_summmary/
cp XS84_03.fa_pseudo/*_log.txt ./pseudo_log_summmary/
