mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_strain_BS3_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_strain_DS1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_UBA141_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_UBA160_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_UBA164_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_UBA183_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_archaeon_UBA57_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Thaumarchaeota_bin_Fn1_renamed.fa.fasta.TCDB.m8 ./
mv /media/ylifc/hdd1/aoa-in-methane-seep-sediment-calculation_steps/Enivronmental_adaptation_gene_detection/orf/cds/TCDB/Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa.fasta.TCDB.m8 ./
