sed -i 's/AAA007-N19/Gen1/' fixed_tree2.tree
sed -i 's/AAA288-D22/Gen2/' fixed_tree2.tree
sed -i 's/AAA799-D07/Gen3/' fixed_tree2.tree
sed -i 's/AAA799-O18/Gen4/' fixed_tree2.tree
sed -i 's/Acidianus_hospitalis_W1/Gen5/' fixed_tree2.tree
sed -i 's/Aciduliprofundum_boonei_T469/Gen6/' fixed_tree2.tree
sed -i 's/Aigarchaeota_archaeon_JGI_0000106_J15/Gen7/' fixed_tree2.tree
sed -i 's/Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18/Gen8/' fixed_tree2.tree
sed -i 's/Aigarchaeota_archaeon_NZ13_MG1/Gen9/' fixed_tree2.tree
sed -i 's/Aigarchaeota_archaeon_strain_OS1/Gen10/' fixed_tree2.tree
sed -i 's/Archaeoglobus_veneficus_SNP6/Gen11/' fixed_tree2.tree
sed -i 's/Caldivirga_maquilingensis_IC_167/Gen12/' fixed_tree2.tree
sed -i 's/Candidatus_Caldiarchaeum_subterraneum/Gen13/' fixed_tree2.tree
sed -i 's/Candidatus_Korarchaeum_cryptofilum_OPF8/Gen14/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosoarchaeum_koreensis_MY1/Gen15/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosocaldus_cavascurensis_strain/Gen146/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosocaldus_islandicus_isolate_3F/Gen17/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosocosmicus_franklandus_C13/Gen18/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosocosmicus_oleophilus_strain/Gen19/' fixed_tree2.tree
sed -i 's/Nitrosopelagicus_brevis_U25/Gen20/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosopelagicus_brevis_strain/Gen21/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosopelagicus_sp_Isolate_GoM/Gen22/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosopumilus_salaria_BD31/Gen23/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrosopumilus_sp_MTA1/Gen24/' fixed_tree2.tree
sed -i 's/Candidatus_Nitrososphaera_evergladensis_SR1/Gen25/' fixed_tree2.tree
sed -i 's/Cenarchaeum_symbiosum_A/Gen26/' fixed_tree2.tree
sed -i 's/EGM_Bin1/Gen27/' fixed_tree2.tree
sed -i 's/EGM_Bin2/Gen28/' fixed_tree2.tree
sed -i 's/Ferroplasma_acidarmanus_fer1/Gen30/' fixed_tree2.tree
sed -i 's/HM45_Bin1/Gen31/' fixed_tree2.tree
sed -i 's/HM45_Bin2/Gen32/' fixed_tree2.tree
sed -i 's/HM58_Bin/Gen33/' fixed_tree2.tree
sed -i 's/HM79_Bin/Gen34/' fixed_tree2.tree
sed -i 's/HM81_Bin1/Gen35/' fixed_tree2.tree
sed -i 's/HM81_Bin2/Gen36/' fixed_tree2.tree
sed -i 's/HM82_Bin1/Gen37/' fixed_tree2.tree
sed -i 's/HM82_Bin2/Gen38/' fixed_tree2.tree
sed -i 's/Haladaptatus_paucihalophilus_DX253/Gen39/' fixed_tree2.tree
sed -i 's/Halogeometricum_borinquense_DSM_11551/Gen40/' fixed_tree2.tree
sed -i 's/Halorhabdus_utahensis_DSM_12940/Gen41/' fixed_tree2.tree
sed -i 's/Halorubrum_lacusprofundi_ATCC_49239/Gen42/' fixed_tree2.tree
sed -i 's/Marine_Group_1_crenarchaeote_sp_SCGC/Gen43/' fixed_tree2.tree
sed -i 's/Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02/Gen44/' fixed_tree2.tree
sed -i 's/Metallosphaera_sedula_DSM_5348/Gen45/' fixed_tree2.tree
sed -i 's/Metallosphaera_yellowstonensis_MK1/Gen46/' fixed_tree2.tree
sed -i 's/Methanocella_arvoryzae_MRE50/Gen47/' fixed_tree2.tree
sed -i 's/Methanocorpusculum_labreanum_Z/Gen48/' fixed_tree2.tree
sed -i 's/Methanopyrus_kandleri_AV19/Gen49/' fixed_tree2.tree
sed -i 's/Methanosarcina_mazei_Go1/Gen50/' fixed_tree2.tree
sed -i 's/Methanothermus_fervidus_DSM_2088/Gen51/' fixed_tree2.tree
sed -i 's/Methanotorris_igneus_Kol_5/Gen52/' fixed_tree2.tree
sed -i 's/Natrialba_magadii_ATCC_43099/Gen53/' fixed_tree2.tree
sed -i 's/Natronomonas_pharaonis_DSM_2160/Gen54/' fixed_tree2.tree
sed -i 's/Nitrosarchaeum_koreense_MY1/Gen55/' fixed_tree2.tree
sed -i 's/Nitrosarchaeum_limnium_BG20/Gen56/' fixed_tree2.tree
sed -i 's/Nitrosarchaeum_limnium_SFB1/Gen57/' fixed_tree2.tree
sed -i 's/Nitrosoarchaeum-Baikal-G1-C1/Gen58/' fixed_tree2.tree
sed -i 's/Nitrosoarchaeum_sp_BD3/Gen59/' fixed_tree2.tree
sed -i 's/Nitrosocosmicus_hydrocola_strain_G61/Gen60/' fixed_tree2.tree
sed -i 's/Nitrosocosmicus_oleophilus_strain_MY3/Gen61/' fixed_tree2.tree
sed -i 's/Nitrosomarinus_catalina_strain_SPOT01/Gen62/' fixed_tree2.tree
sed -i 's/Nitrosopelagicus_brevis_U25/Gen63/' fixed_tree2.tree
sed -i 's/Nitrosopelagicus_brevis_strain_CN25/Gen64/' fixed_tree2.tree
sed -i 's/Nitrosopelagicus_sp_REDSEA-S31_B2/Gen65/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1/Gen66/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2/Gen67/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3/Gen68/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_iota_1/Gen69/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1/Gen70/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2/Gen71/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3/Gen72/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4/Gen73/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5/Gen74/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_adriaticus_strain_NF5/Gen75/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_koreensis_AR1/Gen76/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_maritimus_SCM1/Gen77/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_salaria_BD31/Gen78/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_sediminis_AR2/Gen79/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_sp_D3C/Gen80/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_sp_DDS1/Gen81/' fixed_tree2.tree
sed -i 's/Nitrosopumilus_sp_Nsub/Gen82/' fixed_tree2.tree
sed -i 's/Nitrososphaera_evergladensis_SR1/Gen83/' fixed_tree2.tree
sed -i 's/Nitrososphaera_gargensis_Ga9/Gen84/' fixed_tree2.tree
sed -i 's/Nitrososphaera_viennensis_EN76/Gen85/' fixed_tree2.tree
sed -i 's/Nitrosotalea_bavarica_SbT1/Gen86/' fixed_tree2.tree
sed -i 's/Nitrosotalea_devanaterra_Nd1/Gen87/' fixed_tree2.tree
sed -i 's/Nitrosotalea_koreensis_CS/Gen88/' fixed_tree2.tree
sed -i 's/Nitrosotalea_sinensis_Nd2/Gen89/' fixed_tree2.tree
sed -i 's/Nitrosotalea_sp_CS_isolate_NCS1/Gen90/' fixed_tree2.tree
sed -i 's/Nitrosotenuis_aquarius_strain_AQ6F/Gen91/' fixed_tree2.tree
sed -i 's/Nitrosotenuis_chungbukensis_MY2/Gen92/' fixed_tree2.tree
sed -i 's/Nitrosotenuis_cloacae_strain_SAT1/Gen93/' fixed_tree2.tree
sed -i 's/Picrophilus_torridus_DSM_9790/Gen94/' fixed_tree2.tree
sed -i 's/Pyrobaculum_aerophilum_str_IM2/Gen95/' fixed_tree2.tree
sed -i 's/Pyrobaculum_arsenaticum_DSM_13514/Gen96/' fixed_tree2.tree
sed -i 's/Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2/Gen97/' fixed_tree2.tree
sed -i 's/Pyrobaculum_islandicum_DSM_4184/Gen98/' fixed_tree2.tree
sed -i 's/Pyrococcus_abyssi_GE5/Gen99/' fixed_tree2.tree
sed -i 's/Pyrococcus_furiosus_DSM_3638_2/Gen100/' fixed_tree2.tree
sed -i 's/Pyrococcus_horikoshii_OT3__euryarchaeotes_2/Gen101/' fixed_tree2.tree
sed -i 's/Pyrococcus_yayanosii_CH1/Gen102/' fixed_tree2.tree
sed -i 's/SB_01/Gen103/' fixed_tree2.tree
sed -i 's/SB_02/Gen104/' fixed_tree2.tree
sed -i 's/SMM_01/Gen105/' fixed_tree2.tree
sed -i 's/Saccharolobus_solfataricus_P2/Gen106/' fixed_tree2.tree
sed -i 's/Sulfolobus_acidocaldarius_DSM_639/Gen107/' fixed_tree2.tree
sed -i 's/Sulfolobus_islandicus_L_D_8_5/Gen108/' fixed_tree2.tree
sed -i 's/Sulfolobus_solfataricus_P2/Gen109/' fixed_tree2.tree
sed -i 's/Sulfolobus_tokodaii_str_7/Gen110/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_CSP1-1/Gen145/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_N4/Gen112/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_RBG_16_49_8/Gen113/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_SCGC_AAA007-O23/Gen114/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_UBA141/Gen115/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_UBA160/Gen116/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_UBA164/Gen117/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_UBA183/Gen118/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_UBA57/Gen119/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_isolate_MTA5/Gen120/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_strain_BS3/Gen121/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_strain_BS4/Gen122/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_archaeon_strain_DS1/Gen123/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_bin_Fn1/Gen124/' fixed_tree2.tree
sed -i 's/Thermococcus_barophilus_MP/Gen125/' fixed_tree2.tree
sed -i 's/Thermococcus_gammatolerans_EJ3/Gen126/' fixed_tree2.tree
sed -i 's/Thermococcus_litoralis_DSM_5473/Gen127/' fixed_tree2.tree
sed -i 's/Thermofilum_pendens_Hrk_5/Gen128/' fixed_tree2.tree
sed -i 's/Thermoplasma_acidophilum_DSM_1728/Gen129/' fixed_tree2.tree
sed -i 's/Thermoplasma_volcanium_GSS1/Gen130/' fixed_tree2.tree
sed -i 's/Thermoproteus_tenax_Kra_1/Gen131/' fixed_tree2.tree
sed -i 's/Unclassified_Aigarchaeota_JZ_bin_40/Gen132/' fixed_tree2.tree
sed -i 's/Unclassified_Thaumarchaeota_DRTY_7_bin_36/Gen133/' fixed_tree2.tree
sed -i 's/Vulcanisaeta_distributa_DSM_14429/Gen134/' fixed_tree2.tree
sed -i 's/XS83_01/Gen135/' fixed_tree2.tree
sed -i 's/XS83_02/Gen136/' fixed_tree2.tree
sed -i 's/XS84_01/Gen137/' fixed_tree2.tree
sed -i 's/XS84_02/Gen138/' fixed_tree2.tree
sed -i 's/XS84_03/Gen139/' fixed_tree2.tree
sed -i 's/XS87_01/Gen140/' fixed_tree2.tree
sed -i 's/XS87_02/Gen141/' fixed_tree2.tree
sed -i 's/Thaumarchaeota_YK1309_1N_NP_iota/Gen142/' fixed_tree2.tree
sed -i 's/YK1312_12N_NP_theta/Gen143/' fixed_tree2.tree
sed -i 's/Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1/Gen144/' fixed_tree2.tree
sed -i 's/F/Gen29/' fixed_tree2.tree
